### ISSUE TITLE
"Undefined variable $allowed_html" error on Sa11y's WP admin page

### ISSUE THREAD

**Issue by cbirdsong** [ryersondmp/sa11y-wp#1]
This is error showing up in Query Monitor's error panel when on Sa11y's admin page (/wp-admin/options-general.php?page=sa11y):
```
Undefined variable $allowed_html
```

It appears 14 times:

![](https://user-images.githubusercontent.com/1672206/184990982-33264c77-e225-4eda-95ee-9943e609cf50.png)

In PHP 7.4 it's flagged as a warning, but in 8.0 it's flagged as an error.

**Comment by adamchaboryk** [comment]
Thanks for flagging, @cbirdsong!! I'll fix this next update. 

(sorry for the very slow reply!)
