### ISSUE TITLE
No hint for multiple items in "regions to ignore"

### ISSUE THREAD

**Issue by HUisHU-Christian** [ryersondmp/sa11y-wp#2]
Under "Exclusion" -> "Regions to ignore", the description lacks information about how to add several items. By looking into the code, I found out, that it's a comma separated list, but it would have been easier, if it would have stated clear. Actually it's a CSS selector syntax and it's logical when you think about the implementation, but it could be easier with a simple hint.

This is a duplicate of https://github.com/ryersondmp/sa11y/issues/62 but this is the better place.

**Comment by adamchaboryk** [comment]
Within the Admin settings, under the **Admin Guide** heading, there are instructions to use a comma to separate multiple selectors:

"Create exclusions or ignore repetitive elements using CSS selectors. Use a comma to separate multiple selectors. View [CSS selectors reference.](https://www.w3schools.com/cssref/css_selectors.asp)"

Although this is good feedback, perhaps I can add another description under the Exclusions heading.

**Comment by HUisHU-Christian** [comment]
Now that you mentioned it, I can see it. Unfortunately the box was out of sight for me: too far right (because of a large screen) and scrolled to the top.

Maybe a "position: sticly" could help and an extra hint won't hurt (maybe just a link to the admin guide text on top of the page)

**Comment by adamchaboryk** [comment]
Valid feedback! I work off of a 13''/33cm MacBook screen. 😅

I'll incorporate both in next release (which is soon).
